# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: 
  push:
    branches:
      - main

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the code
        uses: actions/checkout@v2 # This is a reference to some code to run

      - name: Install pyenv
        run: |
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bashrc
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.bashrc
          echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init --path)"\nfi' >> $HOME/.bashrc
          exec "$SHELL"

      - name: Install Python 3.11.0
        run: pyenv install 3.11.0

      - name: Set up Python 3.11.0
        run: pyenv global 3.11.0

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: | # Note that there's no reference here — just commands to run
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      
      # Now we run our tests
      - name: Test with pytest
        run: |
          pipenv run pytest
