# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: 
  push:
    branches:
      - main

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: | # Note that there's no reference here — just commands to run
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      
      # Now we run our tests
      - name: Test with pytest
        run: |
          pipenv run pytest
